### ISSUE TITLE
SciBERT tokenizer not provided

### ISSUE THREAD

**Issue by DENG-Yifan** [MurtyShikhar/ExpBERT#1]
In feature_factory/bert_utils.py, obtain_bert() is initializing a tokenizer by calling `BertTokenizer.from_pretrained('/u/scr/smurty/scibert_scivocab_uncased/vocab.txt', do_lower_case=True)`.
However, the `'/u/scr/smurty/scibert_scivocab_uncased/vocab.txt'` is not provided.
I wonder if you can upload that file, or can I just initialize the tokenizer by `BertTokenizer.from_pretrained('allenai/scibert_scivocab_uncased')`?
Thank you for your work, and for your answer in advance!

**Comment by MurtyShikhar** [comment]
Hello, thank you for interest in our work. We are currently updating the codalab worksheet associated with this paper, so you can then just run all experiments via the worksheet. This should be done soon.

**Comment by DENG-Yifan** [comment]
Thank you for your reply.
I see the codalab worksheet, but there are only codes for the training of classifiers.
Actually I want to generate new features with different explanations using the NLI fine-tuned SciBERT. Thank you for releasing the model parameters, but may I ask for the tokenizer of that model?
(I have tried loading a tokenizer from 'allenai/scibert_scivocab_uncased', but the experiment results are much lower than yours.)

**Comment by DENG-Yifan** [comment]
I have successfully reproduced the results using the 'allenai/scibert_scivocab_uncased' tokenizer for the SciBERT, I think I can close this issue now.
