### ISSUE TITLE
the train network seems not work

### ISSUE THREAD

**Issue by gaoyi-byte** [MurtyShikhar/ExpBERT#3]
I have a problem in running the code.The prediction was 1 at the end of each training session,and the predicition in dev dataset when I use the commond in the readme.Can you tell me where I'm wrong
![image](https://user-images.githubusercontent.com/58095354/103478029-07ee7780-4dff-11eb-8f51-8dc6e8a86741.png)

**Comment by Chiaoso** [comment]
@gaoyi-byte I've met the same problem as you, too. Could you share me how did you solve it?

**Comment by gaoyi-byte** [comment]
Sorry，I do not slove this problem，and i have given up. If you slove this problem hope you can tell me how you slove it.



---Original---
From: ***@***.***&gt;
Date: Thu, Jun 10, 2021 18:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MurtyShikhar/ExpBERT] the train network seems not work (#3)




 
@gaoyi-byte I've met the same problem as you, too. Could you share me how did you solve it?

**Comment by Chiaoso** [comment]
> Sorry，I do not slove this problem，and i have given up. If you slove this problem hope you can tell me how you slove it.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Jun 10, 2021 18:09 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [MurtyShikhar/ExpBERT] the train network seems not work (#3) @gaoyi-byte I've met the same problem as you, too. Could you share me how did you solve it? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

it seems like the default args are incorrect.
